# Generated by Django 3.2.5 on 2021-08-16 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confidentialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(max_length=140, verbose_name='Description')),
                ('nom', models.TextField(max_length=40, verbose_name='Nom')),
                ('can_message', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('confidentialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='confidentialite.confidentialite')),
                ('suivant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivant', to=settings.AUTH_USER_MODEL)),
                ('suivi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivi', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
