# Generated by Django 3.2.5 on 2021-09-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confidentialite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confidentialite',
            name='nom',
        ),
    ]
