# Generated by Django 3.2.5 on 2021-09-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confidentialite', '0002_remove_confidentialite_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confidentialite',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Description'),
        ),
    ]
