# Generated by Django 3.2.5 on 2021-09-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confidentialite', '0003_alter_confidentialite_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confidentialite',
            old_name='description',
            new_name='Description',
        ),
    ]
