# Generated by Django 3.2.5 on 2021-10-26 19:16

import authy.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0004_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=authy.models.user_directory_path, verbose_name='Picture'),
        ),
    ]
