# Generated by Django 3.2.5 on 2021-10-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0005_message_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
    ]
